spring:
    application:
          name: board 6 # ???? ??
    datasource: # ?????? ????
          url: jdbc:mysql://localhost:3306/board
          username: root
          password: green502

mybatis: # Mybatis ??
            mapper-locations: mappers/**/*.xml # xml?? ?? /  mappers?? ???/?? ?????? ???? / .xml? ??? ?? ??

#server:
#  port: 8081 ??? ???? ?? ? ?? ?? 5????, ??? port??? ? ? ?? ??? ?????